#! /bin/bash

set -e; # Caso algum erro aconteça na execução de qualquer comando abaixo, o script será finalizado automaticamente.

# Adiciona chamada do programa no script de inicialização do "bash"
echo -e "\nterminal-initializer" >> /etc/bash.bashrc;
echo "/etc/bash.bashrc modded."

# Cria links para root
mkdir -p -v /root/terminal-initializer && ln -v -s /usr/share/terminal-initializer/files /root/terminal-initializer/files;

# Cria links para usuários comuns
	declare -i NUM_USERS; # A variável NUM_USERS é do tipo inteiro ("int")
	NUM_USERS=`ls -l /home | wc -l`-1; # Quantidade de usuários comuns no sistema
	for ((n=1; n <= NUM_USERS ; n++))
	do
		USER_CHOSEN=$(ls -1 /home | tail -n $n | head -n 1); 

		mkdir -p -v /home/$USER_CHOSEN/terminal-initializer;
		ln -v -s /usr/share/terminal-initializer/files /home/$USER_CHOSEN/terminal-initializer/files;
		chown -v $USER_CHOSEN /home/$USER_CHOSEN/terminal-initializer /home/$USER_CHOSEN/terminal-initializer/files;
	done;
